### ISSUE TITLE
Improvement suggestion on the examples

### ISSUE THREAD

**Issue by fgiacomel** [schnorr/iiufrgs#22]
Just a sugestion: I use TeXstudio for Windows and had to add the line 

\usepackage{epstopdf}

in order to make any example run. I suggest to put it in all examples (don't know if there are other implications on this, tough).

**Comment by kassick** [comment]
We could leave that as a comment in the examples. It actually depends on the user latex environment
a) if you're using a pdf-producing latex distro (i.e. pdflatex, xelatex)
b) if any of your figures are in eps format

It's nothing we could put in the class, but *maybe* we can use a
\ifpdftex
\usepackage{epstopdf}
\else
\ifxetex
\usepackage{epstopdf}
\else
\fi
\fi

in the examples

**Comment by mgmillani** [comment]
I believe this is only necessary because the examples use a .eps file for an image. If that is the case, it makes sense to add it to the examples (commenting that it is only necessary because we include an .eps image).

@fgiacomel If you remove the lines that include fig.eps image, does it work without including this package?

**Comment by fgiacomel** [comment]
Yes, it does.

**Comment by rlerm** [comment]
We could just provide a fig.PDF file and let LaTeX choose.

**Comment by mgmillani** [comment]
Fixed on b01137e8c7e2f06ad35cfa2697455756c0bd7fa6
